### ISSUE TITLE
Compilation fails if no `@template` is specified

### ISSUE THREAD

**Issue by MaKleSoft** [Draccoz/twc#28]
```js
export class MyElement {
    name: string;
}
```
```sh
/Users/martin/.nvm/versions/node/v6.7.0/lib/node_modules/twc/src/PolymerModule.js:149
        let tpl = (({ template, type }) => {
                   ^

TypeError: Cannot match against 'undefined' or 'null'.
    at tpl (/Users/martin/.nvm/versions/node/v6.7.0/lib/node_modules/twc/src/PolymerModule.js:149:20)
    at Module.toString (/Users/martin/.nvm/versions/node/v6.7.0/lib/node_modules/twc/src/PolymerModule.js:156:11)
    at Module.toBuffer (/Users/martin/.nvm/versions/node/v6.7.0/lib/node_modules/twc/src/PolymerModule.js:188:32)
    at DestroyableTransform._transform (/Users/martin/.nvm/versions/node/v6.7.0/lib/node_modules/twc/src/index.js:54:22)
    at DestroyableTransform.Transform._read (/Users/martin/.nvm/versions/node/v6.7.0/lib/node_modules/twc/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (/Users/martin/.nvm/versions/node/v6.7.0/lib/node_modules/twc/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/Users/martin/.nvm/versions/node/v6.7.0/lib/node_modules/twc/node_modules/readable-stream/lib/_stream_writable.js:347:64)
    at writeOrBuffer (/Users/martin/.nvm/versions/node/v6.7.0/lib/node_modules/twc/node_modules/readable-stream/lib/_stream_writable.js:336:5)
    at DestroyableTransform.Writable.write (/Users/martin/.nvm/versions/node/v6.7.0/lib/node_modules/twc/node_modules/readable-stream/lib/_stream_writable.js:274:11)
    at PassThrough.ondata (_stream_readable.js:555:20)
```

**Comment by Draccoz** [comment]
Fixed
