### ISSUE TITLE
Running without parameters fails

### ISSUE THREAD

**Issue by tpluscode** [Draccoz/twc#69]
When I run twc without any parameters it fails with error:

```
\twc\src\cli.js:22
        base = files_1.map(function (file) { return path_1.parse(file).dir; }).reduce(function (a, b) {
                      ^

TypeError: Cannot read property 'map' of null
    at Object.<anonymous> (\twc\src\cli.js:22:23)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:139:18)
    at node.js:999:3
```

**Comment by Draccoz** [comment]
Fixed in #74.
